### ISSUE TITLE
store `clpa.main.json` with identation

### ISSUE THREAD

**Issue by xrotwang** [glottobank/clpa#11]
This would make it a lot easier to read and modify, I guess. Would only need adding a `indent=4` kw arg to `write_CLPA`, I guess.

**Comment by LinguList** [comment]
yep, I agree, and there's no need to minify. The reason I didn't add that line before was only that I realized that manually editing json for handling phonetic characters is a nightmare, so I never really thought of touching the json with my hands, as it will always render unicodes with the \uxxxx numbers, when writing from python, so no human-readability at all. So my strategy in the past was to use my template version and afterwards write back to the json-file with the function in util (I think its something like store_clpa). This is, by the way, one of the things I don't like about json: it's hard to edit it manually, especially when dealing with specific characters...
