### ISSUE TITLE
User-defined symbols or remarks: An idea on how to handle

### ISSUE THREAD

**Issue by LinguList** [glottobank/clpa#34]
Assuming segmented text, we can allow for user-defined symbols, and we can display those consistently in online tools by using some markup, like superscripts or the like. Having spent a long time on thinking how to handle this best, I just realized that the following proposal might work:

* a custom symbol can be represented by an approximate clpa-value and a user-annotated value
* the custom clpa-value can be missing
* the slash is used to separate the approximate value from the user-defined one

As an example, consider "chongniu" readings in Middle Chinese: nobody knows how they should be pronounced, but they are kept distinct in many sources, so we could just represent them as follows:

Chinese | Baxter1992 | IPA | CLPA (with custom symbols) 
--- | --- | --- | --- 
幨  chān | tsyhem | tɕʰiem | `tɕʰ j/ji e m
餰 qiān | tsyen | tɕiem | `tɕʰ j/j e m

Note that I'm note sure whether there really is the difference in the official final in the palatal series, but one could distinguish these Chongniu cases in such a way.

When representing Laryngeals in PIE, one could likewise write things like `p ə/h₂ t e: r`. Or simply `p /h₂ t e: r`, and it would be easy to display both forms or only one later.

**Comment by LinguList** [comment]
Let us put this into a test: If a fallback (a phonetic value) is assigned by the user, this should yield:

```python
>>> clpa.check_sequence('p h₂/x t e r')
(['p', 'x', 't', 'e', 'r'],
 {'p': {'frequency': 1, 'id': 'c288', 'clpa': 'p'},
  'h₂/x': {'frequency': 1, 'id': 'c772', 'clpa': 'x'},
  'e': {'frequency': 1, 'id': 'v200', 'clpa': 'e'},
  't': {'frequency': 1, 'id': 'c118', 'clpa': 't'},
  'r': {'frequency': 1, 'id': 'c151', 'clpa': 'r'}},
 Counter({'convertable': 1, 'custom': 0, 'non-convertable': 0}))
```

Note the new keyword "custom", indicating custom values. Here, it is simply for the convenience of the researcher, wishing to preserve the original ```h₂```, although the researcher commits to a phonetic intepretation (not matter how coarse this will be).

If the value is not specified, we still don't want to blame researchers for submitting errors, so this will yield the following output:

```python
>>> clpa.check_sequence('p h₂/ t e r')
(['p', '*h₂', 't', 'e', 'r'],
 {'p': {'frequency': 1, 'id': 'c288', 'clpa': 'p'},
  't': {'frequency': 1, 'id': 'c118', 'clpa': 't'},
  'e': {'frequency': 1, 'id': 'v200', 'clpa': 'e'},
  'h₂/': {'frequency': 1, 'id': 'custom:h₂', 'clpa': '*h₂'},
  'r': {'frequency': 1, 'id': 'c151', 'clpa': 'r'}},
 Counter({'custom': 1, 'convertable': 0, 'non-convertable': 0}
```

This is a first suggestion.

**Comment by LinguList** [comment]
Note that in this way we can also handle tone sandhi annotation:

```python
>>> clpa.check_sequence('p a ¹/²')
(['p', 'a', '²'],
 {'a': {'frequency': 1, 'id': 'v130', 'clpa': 'a'},
  '¹/²': {'frequency': 1, 'id': 't001', 'clpa': '²'},
  'p': {'frequency': 1, 'id': 'c288', 'clpa': 'p'}},
 Counter({'convertable': 1, 'custom': 0, 'non-convertable': 0}))
```
This is useful, as in most cases we do not want to store the tone sandhis for our segment inventories in lexibank, but people might want to retain this information.

**Comment by xrotwang** [comment]
For a moment I thought the `/` above was a superscript, too... But what you are saying is that `/` appears in segmented data, not in the original transcriptions, right? So how does it get into the segments? Profiles?

**Comment by LinguList** [comment]
Yes! This should be the ONLY way to create that kind of data, as it would otherwise interfere. I think it is safe to use the "/", as it is easy to type (advantage), easy to interpret (the semantics, I mean), and it is only used in segmented text, so it is a clear format description, also in the light of CLDF.

**Comment by LinguList** [comment]
Since the Sandhi is annotated in many Chinese datasets, we could avoid many errors in this way. We'd also be able to add all kinds of proto-languages, without having to bother with the real pronunciation if this is not provided.

**Comment by xrotwang** [comment]
Oh yes, good idea! Getting proto languages into the system would be really cool.

**Comment by LinguList** [comment]
This is also, why I chose that "h₂" example, or how I realized we might need this, as Nathan was bringing up that he has to sounds "o1" and "o2" in Old Burmese, but nobody knows how to pronounce those vowels. Guess these are the classical examples. One might even make an extra-case for tone sandhi, but I'd say we treat it as a user-custom for the moment, as there are no applications that take tone sandhi really into account, and we won't loose information.

**Comment by xrotwang** [comment]
What would be the best place for a library to handle this kind of sequence notation? CLPA? Or pycldf? One nice aspect of this notation is that it doesn't interfere with simple analyses like counting segments.

**Comment by xrotwang** [comment]
LingPy would probably be good candidate, because it is likely the first place where any use is made of this kind of information, but it may not be the best place to foster usage and uptake?

**Comment by xrotwang** [comment]
Thinking about it more - and about the fact that profiles will be the way to code and store the meta-information - maybe `segments` would need a proper `Sequence` class, which provides access to the tiers of information?

**Comment by xrotwang** [comment]
I do hope one can get away with this notation, though, without having to realize that multiple annotation tiers are truly needed ...

**Comment by LinguList** [comment]
Yes, having a Sequence class in CLDF would be desirable, as this will further advance, and I imagine that CLPA information coud also be handled in this way, right?

**Comment by LinguList** [comment]
LingPy should react on this notation by checking for sound class and conversion only the element AFTER the "/", in the tokens2class function, which is easy to do. For clpa, I'm preparing a PR, and for lexibank, I am preparing an orthoprofile for one Chinese dataset illustrating this behavior.

We should not encourage people to only use custom symbols, since this will just create the problems we want to avoid, but allowing scholars to keep their proto-forms and explicitly decide on specific phonetic values to allow the machinese to interprete them seems like a good idea for alignments, and all other kinds of analyses.

**Comment by xrotwang** [comment]
This notation actually also opens up a way to round-trip lexical data. So this is what should be used to create new data for say ASJP :)

**Comment by LinguList** [comment]
What I also imagine for the nearer future is to have a nice display where users can choose one variant in alignments: the phonetic variant, or the classical one. With JavaScript, this is no problem, and even if it looks a bit ugly in raw string, it can be prettified easily.

**Comment by LinguList** [comment]
And just an example for the ortho-profiles with this annotation: Dataset "yinku" before had 162 segments, and 15 clpa errors, WITHOUT the tone sandhi combinations in the data, now it has:

* **Segments:** 54 (1 LingPy errors, 1 CLPA errors, 11 CLPA modified)

**Comment by LinguList** [comment]
Oh, that is an error, I just realized, as the ortho-profiles were not used, apparently.
