### ISSUE TITLE
basic workflow for clpa analysis

### ISSUE THREAD

**Issue by LinguList** [glottobank/clpa#35]
we should refine the workflow and make it more explicit. Right now, I see the following steps as important:

1. normalization (NFC, NFD, unicode, just an internal issue)
2. normalization by avoiding confusables from unicode (like the numerous Schwa sounds and the like)
3. standardization by converting frequently used non-IPA characters, like š, č, to their most likely counterparts (here, not everybody may agree, but I consider this as useful)
3. re-fining of characters, as it is done in phoible (so tʂ should be re-written as ʈʂ, as the t is usually retroflex, but people don't spell it out)
4. re-ordering of characters, as it is done in phoible
5. segmenting characters, using an explicit orthography profile

I don't know whether we need more steps or less here, but "ordering", and the different standardization steps seem to be crucial. 
5.

**Comment by xrotwang** [comment]
This is mostly processing **before** analyzing for CLPA conformance, right? So most of this would, e.g. be implemented in orthography profiles. So I guess we can close the issue here.

**Comment by LinguList** [comment]
Yes!
